<a href="https://colab.research.google.com/github/willystumblr/AI-ML_Team_5/blob/main/MIMIC_III_preprocess_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
featureID = {220045: 2762225,
 220210: 2737105,
 220277: 2671816,
 1125: 2955851,
 128: 3216866,
 159: 2544519,
 161: 3236350,
 211: 5180809,
 212: 3303151,
 550: 3205052,
 618: 3386719,
 646: 3418917,
 742: 3464326,
 1484: 2261065,
 52: 2072743,
 51: 2096678,
 5815: 1807316,
 5819: 1772387,
 5820: 1802684,
 8549: 1804988,
 8553: 1769925,
 8554: 1796313,
 8368: 2085994,
 224650: 1849287,
 220048: 2023672,
 227969: 1862707}

In [ ]:
len(featureID.keys())

26

In [ ]:
import glob
import numpy as np
import pandas as pd
import os
# Additional libraries...
import tqdm
import pickle
from collections import defaultdict

In [ ]:
datadir = "/content/drive/MyDrive/dataset/physionet.org/files/mimiciii/1.4"
tables = {
    "CHARTEVENTS":"CHARTEVENTS.csv",
    "ICUSTAYS":"ICUSTAYS.csv",
    "ADMISSIONS":"ADMISSIONS.csv",
    "PATIENTS":"PATIENTS.csv",
    "D_ITEMS":"D_ITEMS.csv"
}

In [ ]:
icustays = pd.read_csv(os.path.join(datadir, tables['ICUSTAYS']))
icustay_id = icustays[(icustays['LOS'] > 24/24.0) & (icustays['LOS'] < 48/24.0)]

# TEST

In [ ]:
for chunk in pd.read_csv(os.path.join(datadir, tables['CHARTEVENTS']), chunksize=100000):
    break

In [ ]:
chunk['CHARTTIME'] = pd.to_datetime(chunk['CHARTTIME']).dt.floor('H')
filtered = chunk.groupby('ICUSTAY_ID').apply(filter_first_3_hours)
filtered

                  ROW_ID  SUBJECT_ID  HADM_ID  ICUSTAY_ID  ITEMID  \
ICUSTAY_ID
201272.0   21360   26702         154   102354    201272.0  220045
           21361   26703         154   102354    201272.0  220210
           21362   26704         154   102354    201272.0  220179
           21363   26705         154   102354    201272.0  220180
           21364   26706         154   102354    201272.0  220181
...                  ...         ...      ...         ...     ...
299707.0   54652   52013         402   167615    299707.0  220210
           54653   52014         402   167615    299707.0  220277
           54654   52015         402   167615    299707.0  220179
           54655   52016         402   167615    299707.0  220180
           54656   52017         402   167615    299707.0  220181

                           CHARTTIME            STORETIME   CGID  VALUE  \
ICUSTAY_ID
201272.0   21360 2127-12-23 22:00:00  2127-12-23 22:09:00  14719   84.0
           21361 2127-12-23 22:00:00  2127-12-23 22:09:00  14719   15.0
           21362 2127-12-23 22:00:00  2127-12-23 22:09:00  14719  113.0
           21363 2127-12-23 22:00:00  2127-12-23 22:09:00  14719   74.0
           21364 2127-12-23 22:00:00  2127-12-23 22:09:00  14719   83.0
...                              ...                  ...    ...    ...
299707.0   54652 2156-11-11 23:00:00  2156-11-11 23:58:00  21058   21.0
           54653 2156-11-11 23:00:00  2156-11-11 23:58:00  21058   94.0
           54654 2156-11-11 23:00:00  2156-11-11 23:58:00  21058   92.0
           54655 2156-11-11 23:00:00  2156-11-11 23:58:00  21058   58.0
           54656 2156-11-11 23:00:00  2156-11-11 23:58:00  21058   66.0

                  VALUENUM  VALUEUOM  WARNING  ERROR  RESULTSTATUS  STOPPED
ICUSTAY_ID
201272.0   21360      84.0       bpm        0      0           NaN      NaN
           21361      15.0  insp/min        0      0           NaN      NaN
           21362     113.0      mmHg        0      0           NaN      NaN
           21363      74.0      mmHg        0      0           NaN      NaN
           21364      83.0      mmHg        0      0           NaN      NaN
...                    ...       ...      ...    ...           ...      ...
299707.0   54652      21.0  insp/min        0      0           NaN      NaN
           54653      94.0         %        0      0           NaN      NaN
           54654      92.0      mmHg        0      0           NaN      NaN
           54655      58.0      mmHg        0      0           NaN      NaN
           54656      66.0      mmHg        0      0           NaN      NaN

[5159 rows x 15 columns]

In [ ]:
grouped = chunk.

In [ ]:
chunk[chunk['ICUSTAY_ID'].isin(icustay_id['ICUSTAY_ID'])]

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,CGID,VALUE,VALUENUM,VALUEUOM,WARNING,ERROR,RESULTSTATUS,STOPPED
73,326,34,144319,290505.0,220180,2191-02-23 05:30:00,2191-02-23 07:45:00,17741,66.0,66.0,mmHg,0,0,NaN,NaN
74,327,34,144319,290505.0,220181,2191-02-23 05:30:00,2191-02-23 07:45:00,17741,78.0,78.0,mmHg,0,0,NaN,NaN
75,328,34,144319,290505.0,223875,2191-02-23 07:00:00,2191-02-23 07:36:00,16924,10.0,10.0,insp/min,0,0,NaN,NaN
76,329,34,144319,290505.0,224690,2191-02-23 07:00:00,2191-02-23 07:35:00,16924,22.0,22.0,insp/min,0,0,NaN,NaN
77,330,34,144319,290505.0,224696,2191-02-23 07:00:00,2191-02-23 07:35:00,16924,16.0,16.0,cmH2O,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23658,14792,109,196721,217934.0,220045,2142-07-17 10:00:00,2142-07-17 10:14:00,18566,106.0,106.0,bpm,0,0,NaN,NaN
23659,14793,109,196721,217934.0,220179,2142-07-17 10:00:00,2142-07-17 10:14:00,18566,188.0,188.0,mmHg,0,0,NaN,NaN
23660,14794,109,196721,217934.0,220180,2142-07-17 10:00:00,2142-07-17 10:14:00,18566,110.0,110.0,mmHg,0,0,NaN,NaN
23661,14795,109,196721,217934.0,220181,2142-07-17 10:00:00,2142-07-17 10:14:00,18566,128.0,128.0,mmHg,0,0,NaN,NaN
23662,14796,109,196721,217934.0,220210,2142-07-17 10:00:00,2142-07-17 10:14:00,18566,33.0,33.0,insp/min,0,0,NaN,NaN

In [ ]:
icustay_id.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,DBSOURCE,FIRST_CAREUNIT,LAST_CAREUNIT,FIRST_WARDID,LAST_WARDID,INTIME,OUTTIME,LOS
4,369,272,164716,210407,carevue,CCU,CCU,57,57,2186-12-25 21:08:04,2186-12-27 12:01:13,1.6202
5,370,273,158689,241507,carevue,MICU,MICU,52,52,2141-04-19 06:12:05,2141-04-20 17:52:11,1.4862
8,373,276,135156,206327,carevue,CCU,CCU,57,57,2147-11-20 09:02:23,2147-11-21 17:08:52,1.3378
16,381,284,112354,223593,carevue,MICU,MICU,12,12,2149-11-29 15:39:34,2149-11-30 17:18:14,1.0685
19,384,286,135917,240627,carevue,SICU,SICU,57,57,2176-04-10 20:46:09,2176-04-12 16:42:47,1.8310

In [ ]:
admissions = pd.read_csv(os.path.join(datadir, tables['ADMISSIONS']))

In [ ]:
patients = pd.read_csv(os.path.join(datadir, tables['PATIENTS']))
patients.head()

,ROW_ID,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG
0,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0
1,235,250,F,2164-12-27 00:00:00,2188-11-22 00:00:00,2188-11-22 00:00:00,NaN,1
2,236,251,M,2090-03-15 00:00:00,NaN,NaN,NaN,0
3,237,252,M,2078-03-06 00:00:00,NaN,NaN,NaN,0
4,238,253,F,2089-11-26 00:00:00,NaN,NaN,NaN,0

In [ ]:
tmp = icustay_id.merge(patients[['DOB', 'SUBJECT_ID']], on='SUBJECT_ID', how='left')
pd.to_datetime(tmp['OUTTIME']).dt.year - pd.to_datetime(tmp['DOB']).dt.year

0        67
1        34
2        35
3        87
4        86
         ..
16893    58
16894    69
16895    88
16896    69
16897    69
Length: 16898, dtype: int64

In [ ]:
admissions.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,DISC-TRAN CANCER/CHLDRN H,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2196-04-09 10:06:00,2196-04-09 13:24:00,BENZODIAZEPINE OVERDOSE,0,1
1,22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,0,1
2,23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,BRAIN MASS,0,1
3,24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,NaN,NaN,INTERIOR MYOCARDIAL INFARCTION,0,1
4,25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2160-11-02 01:01:00,2160-11-02 04:27:00,ACUTE CORONARY SYNDROME,0,1

In [ ]:
admissions['HADM_ID'][pd.notna(admissions['DEATHTIME'])]

9        128652
57       181711
63       189535
70       155252
88       166401
          ...
58927    108710
58957    185764
58966    127022
58970    105447
58972    101071
Name: HADM_ID, Length: 5854, dtype: int64

In [ ]:
patients['MORTALITY'] = patients['SUBJECT_ID'].isin(admissions['SUBJECT_ID'][pd.notna(admissions['DEATHTIME'])])

In [ ]:
patients['MORTALITY']

0        False
1         True
2        False
3        False
4        False
         ...
46515    False
46516    False
46517     True
46518    False
46519    False
Name: MORTALITY, Length: 46520, dtype: bool

In [ ]:
len(patients)

46520

In [ ]:
newdf = chunk.merge(admissions[['HADM_ID', 'DIAGNOSIS']], on='HADM_ID', how='left')
newdf

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,CGID,VALUE,VALUENUM,VALUEUOM,WARNING,ERROR,RESULTSTATUS,STOPPED,DIAGNOSIS
0,788,36,165660,241249.0,223834,2134-05-12 12:00:00,2134-05-12 13:56:00,17525,15.00,15.00,L/min,0,0,NaN,NaN,VENTRAL HERNIA/SDA
1,789,36,165660,241249.0,223835,2134-05-12 12:00:00,2134-05-12 13:56:00,17525,100.00,100.00,NaN,0,0,NaN,NaN,VENTRAL HERNIA/SDA
2,790,36,165660,241249.0,224328,2134-05-12 12:00:00,2134-05-12 12:18:00,20823,0.37,0.37,NaN,0,0,NaN,NaN,VENTRAL HERNIA/SDA
3,791,36,165660,241249.0,224329,2134-05-12 12:00:00,2134-05-12 12:19:00,20823,6.00,6.00,min,0,0,NaN,NaN,VENTRAL HERNIA/SDA
4,792,36,165660,241249.0,224330,2134-05-12 12:00:00,2134-05-12 12:19:00,20823,2.50,2.50,NaN,0,0,NaN,NaN,VENTRAL HERNIA/SDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,35618,188,132401,292343.0,220181,2162-01-13 07:00:00,2162-01-13 07:19:00,17249,66.00,66.00,mmHg,0,0,NaN,NaN,BACK PAIN
29996,35619,188,132401,292343.0,220210,2162-01-13 07:00:00,2162-01-13 07:19:00,17249,28.00,28.00,insp/min,0,0,NaN,NaN,BACK PAIN
29997,35620,188,132401,292343.0,220277,2162-01-13 07:00:00,2162-01-13 07:19:00,17249,97.00,97.00,%,0,0,NaN,NaN,BACK PAIN
29998,35621,188,132401,292343.0,224404,2162-01-13 07:37:00,2162-01-13 07:37:00,17249,1.90,1.90,mL,0,0,NaN,NaN,BACK PAIN
29999,35622,188,132401,292343.0,224406,2162-01-13 07:37:00,2162-01-13 07:37:00,17249,2.00,2.00,mL,0,0,NaN,NaN,BACK PAIN

# REAL

In [ ]:
dtypes = pickle.load(open(os.path.join(datadir, 'dtypes.pkl'), 'rb'))
# obj = dtypes[220048]
# for k in [128, 159, 161, 550, 212, 1125, 1484]:
#     dtypes[k] = obj

In [ ]:
dtypes

{'ICUSTAY_ID': dtype('float64'),
 'HADM_ID': dtype('int64'),
 'SUBJECT_ID': dtype('int64'),
 220048: dtype('O'),
 224650: dtype('O'),
 227969: dtype('O'),
 220045: dtype('float64'),
 220210: dtype('float64'),
 220277: dtype('float64'),
 1125: dtype('O'),
 128: dtype('O'),
 159: dtype('O'),
 161: dtype('O'),
 211: dtype('float64'),
 212: dtype('O'),
 550: dtype('O'),
 618: dtype('float64'),
 646: dtype('float64'),
 742: dtype('float64'),
 1484: dtype('O'),
 52: dtype('float64'),
 51: dtype('float64'),
 5815: dtype('float64'),
 5819: dtype('float64'),
 5820: dtype('float64'),
 8549: dtype('float64'),
 8553: dtype('float64'),
 8554: dtype('float64'),
 8368: dtype('float64')}

In [ ]:
def pivot(df):
    df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])
    # df.drop(columns=['ROW_ID','STORETIME', 'CGID','WARNING', 'ERROR', 'RESULTSTATUS', 'STOPPED'])

    pivoted_df = df.pivot_table(index=['ICUSTAY_ID','HADM_ID', 'SUBJECT_ID', 'CHARTTIME'], columns='ITEMID', values='VALUE', aggfunc='first')
    pivoted_df.reset_index(inplace=True)
    return pivoted_df

In [ ]:
def filter_first_3_hours(group):
    min_time = group['CHARTTIME'].min()
    time_threshold = min_time + pd.Timedelta(hours=3)
    return group[group['CHARTTIME'] <= time_threshold]

In [ ]:
def adjust_dataframe(df, target_columns, essential_columns, dtype_dict):
    # Ensure target_columns is a list
    # if not isinstance(target_columns, list):
    #     target_columns = [target_columns]

    # Add target columns to desired_columns list if they are not already there
    desired_columns = list(set(target_columns + essential_columns))

    # Add each target column to the DataFrame if it doesn't exist
    for col in target_columns:
        if col not in df.columns:
            df[col] = np.nan

    # Drop columns not in the desired columns list, while preserving essential columns
    columns_to_drop = set(df.columns) - set(desired_columns)
    df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

    # Set the data type for each column based on the dtype_dict
    for col in df.columns:
        if col in dtype_dict:
            df[col] = df[col].astype(dtype_dict[col])

    grouped = df.groupby('ICUSTAY_ID').apply(filter_first_3_hours)
    # assert len(grouped.columns) == 30
    return grouped

In [ ]:
def aggregate(df, group, identifiers=['ICUSTAY_ID','HADM_ID', 'SUBJECT_ID']):
    # cat = list(df.drop(columns=identifiers).select_dtypes(include=['object']).columns)
    # num = list(df.drop(columns=identifiers).select_dtypes(include=['float64', 'int64']).columns)
    # assert set(cat)+set(num) == set(features)
    aggregations = {}
    for col, dtype in df.drop(columns=identifiers).dtypes.items():
        if dtype in ['int64', 'float64']:  # Replace with appropriate numeric types
            aggregations[col] = 'mean'
        elif dtype == 'object':  # Assuming 'object' dtype are categorical
            aggregations[col] = 'first'
        # Add more conditions if needed

    agged = df.groupby(group).agg(aggregations).reset_index()

    assert len(agged.columns) == 30
    return agged

In [ ]:
def add_features(df, features):

    if 'ADMISSIONS' in features:
        ref = pd.read_csv(os.path.join(datadir, tables['ADMISSIONS']))
        df['MORTALITY'] = df['HADM_ID'].isin(ref['HADM_ID'][pd.notna(ref['DEATHTIME'])])
        df['MORTALITY'] = df['MORTALITY'].astype('bool')
        df = df.merge(ref[['HADM_ID', 'DIAGNOSIS']], on='HADM_ID', how='left')

    if 'PATIENTS' in features and 'ICUSTAYS' in features:
        ref1 = pd.read_csv(os.path.join(datadir, tables['PATIENTS']))
        ref2 = pd.read_csv(os.path.join(datadir, tables['ICUSTAYS']))

        df = df.merge(ref1[['DOB', 'SUBJECT_ID']], on='SUBJECT_ID', how='left')
        df = df.merge(ref2[['ICUSTAY_ID', 'OUTTIME']], on='ICUSTAY_ID', how='left')
        df['AGE'] = pd.to_datetime(df['OUTTIME']).dt.year - pd.to_datetime(df['DOB']).dt.year
        df.loc[df['AGE'] >= 300, 'AGE'] = df['AGE'] - 250
        df['AGE'] = df['AGE'].astype('float64')

        df.drop(columns = ['DOB', 'OUTTIME'], inplace=True)

    return df

In [ ]:
def fill_nan(df):
    original = df.columns
    fix = ['HADM_ID', 'ICUSTAY_ID', 'SUBJECT_ID', 'AGE', 'MORTALITY', 'DIAGNOSIS', 'CHARTTIME', 'IS_DUMMY_ROW']
    for col in df.columns:
        if col in fix:
            continue
        df["HAS_"+str(col)] = np.nan
        df["HAS_"+str(col)] = df["HAS_"+str(col)].astype('bool')

    # Add indicators
    for i in range(len(df)):
        for col in original:
            if col in fix:
                continue
            else:
                if pd.notna(df.loc[i, col]):
                    df.loc[i, "HAS_"+str(col)] = True
                    continue
                else:
                    df.loc[i, "HAS_"+str(col)] = False
                    df.loc[i, col]= 'None' if df[col].dtypes == 'object' else 0


    return df

## Test with a sample

In [ ]:
targets = featureID.keys()
essentials = ['ICUSTAY_ID', 'HADM_ID', 'AGE', 'MORTALITY', 'SUBJECT_ID', 'DIAGNOSIS', 'CHARTTIME']
# ['ICUSTAY_ID', 'HADM_ID']
testdf = chunk[chunk['ICUSTAY_ID'].isin(icustay_id['ICUSTAY_ID'])]
testdf = pivot(testdf)
testdf

<ipython-input-19-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

ITEMID,ICUSTAY_ID,HADM_ID,SUBJECT_ID,CHARTTIME,220045,220046,220047,220050,220051,220052,...,227468,227471,227537,227538,227565,227566,227579,227580,227581,227582
0,217934.0,196721,109,2142-07-17 08:00:00,100.0,120.0,50.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,217934.0,196721,109,2142-07-17 08:01:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,217934.0,196721,109,2142-07-17 08:11:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,217934.0,196721,109,2142-07-17 08:12:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,217934.0,196721,109,2142-07-17 08:57:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1718,299251.0,131376,109,2142-07-08 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1719,299251.0,131376,109,2142-07-08 16:08:00,89.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1720,299251.0,131376,109,2142-07-08 16:10:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1721,299251.0,131376,109,2142-07-08 16:11:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1722,299251.0,174489,109,2142-07-08 06:14:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
testdf = adjust_dataframe(testdf, list(targets), essentials, dtypes)

testdf

ITEMID           ICUSTAY_ID  HADM_ID  SUBJECT_ID           CHARTTIME  220045  \
ICUSTAY_ID
217934.0   0       217934.0   196721         109 2142-07-17 08:00:00   100.0
           1       217934.0   196721         109 2142-07-17 08:01:00     NaN
           2       217934.0   196721         109 2142-07-17 08:11:00     NaN
           3       217934.0   196721         109 2142-07-17 08:12:00     NaN
           4       217934.0   196721         109 2142-07-17 08:57:00     NaN
...                     ...      ...         ...                 ...     ...
299251.0   1670    299251.0   131376         109 2142-07-07 12:00:00    81.0
           1671    299251.0   131376         109 2142-07-07 12:01:00     NaN
           1672    299251.0   131376         109 2142-07-07 12:33:00     NaN
           1673    299251.0   131376         109 2142-07-07 13:00:00    86.0
           1674    299251.0   131376         109 2142-07-07 14:00:00    90.0

ITEMID           220210  220277 1125  128  159  ... 5815  5819 5820 8549  \
ICUSTAY_ID                                      ...
217934.0   0       17.0    99.0  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           1        NaN     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           2        NaN     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           3        NaN     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           4        NaN     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
...                 ...     ...  ...  ...  ...  ...  ...   ...  ...  ...
299251.0   1670    10.0     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           1671     NaN   100.0  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           1672     NaN     NaN  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           1673    20.0   100.0  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN
           1674    18.0   100.0  NaN  NaN  NaN  ...  NaN   NaN  NaN  NaN

ITEMID           8553  8554  8368 224650  220048  227969
ICUSTAY_ID
217934.0   0      NaN   NaN   NaN    NaN     NaN     NaN
           1      NaN   NaN   NaN    NaN     NaN     NaN
           2      NaN   NaN   NaN    NaN     NaN     NaN
           3      NaN   NaN   NaN    NaN     NaN     NaN
           4      NaN   NaN   NaN    NaN     NaN     NaN
...               ...   ...   ...    ...     ...     ...
299251.0   1670   NaN   NaN   NaN    NaN     NaN     NaN
           1671   NaN   NaN   NaN    NaN     NaN     NaN
           1672   NaN   NaN   NaN    NaN     NaN     NaN
           1673   NaN   NaN   NaN    NaN     NaN     NaN
           1674   NaN   NaN   NaN    NaN     NaN     NaN

[332 rows x 30 columns]

In [ ]:
import pickle
with open(os.path.join(datadir, 'dtypes.pkl'), 'wb') as f:
    pickle.dump(dtypes, f)

In [ ]:
testdf = add_features(testdf, ['PATIENTS', 'ICUSTAYS', 'ADMISSIONS'])
testdf

,ICUSTAY_ID,HADM_ID,SUBJECT_ID,CHARTTIME,220045,220210,220277,1125,128,159,...,8553,8554,8368,224650,220048,227969,MORTALITY,DIAGNOSIS,AGE,IS_DUMMY_ROW
0,217934.0,196721,109,2142-07-17 08:00:00,100.0,17.0,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,True
1,217934.0,196721,109,2142-07-17 08:01:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,True
2,217934.0,196721,109,2142-07-17 08:11:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,True
3,217934.0,196721,109,2142-07-17 08:12:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,True
4,217934.0,196721,109,2142-07-17 08:57:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,299251.0,131376,109,2142-07-07 12:00:00,81.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
328,299251.0,131376,109,2142-07-07 12:01:00,NaN,NaN,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
329,299251.0,131376,109,2142-07-07 12:33:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
330,299251.0,131376,109,2142-07-07 13:00:00,86.0,20.0,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
331,299251.0,131376,109,2142-07-07 14:00:00,90.0,18.0,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True

### **SKIP THIS PART**

In [ ]:
def process_patient(df_grouped):
    patient_data = df_grouped.sort_values(by='CHARTTIME')

    # Process data for each 3-hour window
    # ...

    # Add dummy rows if necessary and apply ffill
    while len(patient_data) < 3:
        patient_data = patient_data.append(pd.Series(), ignore_index=True)
        patient_data.iloc[-1, :] = patient_data.iloc[-2, :]  # Forward fill the last row
        patient_data.at[len(patient_data) - 1, 'IS_DUMMY_ROW'] = True  # Set is_dummy flag for dummy row

    return patient_data

In [ ]:
grouped = testdf.groupby('ICUSTAY_ID')
dfs = pd.concat([process_patient(group) for name, group in grouped]).reset_index(drop=True)
dfs['IS_DUMMY_ROW'] = dfs['IS_DUMMY_ROW'].fillna(False).astype(bool)
dfs

<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-58-ca662ddd3b4d>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  patient_data = patient_data.append(pd.Series(), ignore_index=True)
<ipython-input-62-38dd8e96ea8f>:2: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  dfs = pd.concat([process_patient(group) for name, group in grouped]).reset_index(drop=True)

,ICUSTAY_ID,HADM_ID,SUBJECT_ID,CHARTTIME,220045,220210,220277,1125,128,159,...,8553,8554,8368,224650,220048,227969,MORTALITY,DIAGNOSIS,AGE,IS_DUMMY_ROW
0,217934.0,196721.0,109.0,2142-07-17 08:00:00,100.0,17.0,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,False
1,217934.0,196721.0,109.0,2142-07-17 09:00:00,100.0,39.0,91.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,False
2,217934.0,196721.0,109.0,2142-07-17 10:00:00,106.0,33.0,92.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SHORTNESS OF BREATH,25.0,False
3,225073.0,134369.0,124.0,2165-05-30 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,CLAUDICATION,75.0,False
4,225073.0,134369.0,124.0,2165-05-30 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,CLAUDICATION,75.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,298214.0,115629.0,518.0,2109-12-30 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,DIPLOPIA,47.0,False
104,298214.0,115629.0,518.0,2109-12-30 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,DIPLOPIA,47.0,True
105,299251.0,131376.0,109.0,2142-07-07 11:00:00,88.0,15.0,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,False
106,299251.0,131376.0,109.0,2142-07-07 12:00:00,81.0,10.0,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,False
107,299251.0,131376.0,109.0,2142-07-07 13:00:00,86.0,20.0,100.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,False

In [ ]:
dfs.tail(15)

,index,ICUSTAY_ID,HADM_ID,SUBJECT_ID,CHARTTIME,220045,220210,220277,1125,128,...,8553,8554,8368,224650,220048,227969,MORTALITY,DIAGNOSIS,AGE,IS_DUMMY_ROW
93,91,291270.0,113189.0,109.0,2142-02-14 11:00:00,97.0,16.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
94,92,291270.0,113189.0,109.0,2142-02-14 12:00:00,96.0,16.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
95,93,291270.0,113189.0,109.0,2142-02-14 13:00:00,95.0,NaN,99.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
96,94,291697.0,112077.0,85.0,2167-07-25 21:00:00,136.0,39.0,99.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,PNEUMONIA,77.0,True
97,95,291697.0,112077.0,85.0,2167-07-25 22:00:00,131.0,32.0,98.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,PNEUMONIA,77.0,True
98,96,291697.0,112077.0,85.0,2167-07-25 23:00:00,125.0,36.0,98.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,PNEUMONIA,77.0,True
99,97,293876.0,186251.0,266.0,2168-07-10 09:00:00,85.0,16.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SEIZURE,78.0,True
100,98,293876.0,186251.0,266.0,2168-07-10 10:00:00,81.0,17.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SEIZURE,78.0,True
101,99,293876.0,186251.0,266.0,2168-07-10 11:00:00,83.0,16.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,SEIZURE,78.0,True
102,0,298214.0,115629.0,518.0,2109-12-29 19:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,DIPLOPIA,47.0,True
103,1,298214.0,115629.0,518.0,2109-12-30 03:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,DIPLOPIA,47.0,True
104,2,298214.0,115629.0,518.0,2109-12-30 03:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,DIPLOPIA,47.0,True
105,102,299251.0,131376.0,109.0,2142-07-07 11:00:00,88.0,15.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
106,103,299251.0,131376.0,109.0,2142-07-07 12:00:00,81.0,10.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True
107,104,299251.0,131376.0,109.0,2142-07-07 13:00:00,86.0,20.0,100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,False,HYPERTENSION,25.0,True

### **START FROM HERE**

In [ ]:
testdf = fill_nan(testdf)
testdf

,ICUSTAY_ID,HADM_ID,SUBJECT_ID,CHARTTIME,220045,220210,220277,1125,128,159,...,HAS_5815,HAS_5819,HAS_5820,HAS_8549,HAS_8553,HAS_8554,HAS_8368,HAS_224650,HAS_220048,HAS_227969
0,217934.0,196721,109,2142-07-17 08:00:00,100.0,17.0,99.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
1,217934.0,196721,109,2142-07-17 08:01:00,0.0,0.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
2,217934.0,196721,109,2142-07-17 08:11:00,0.0,0.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
3,217934.0,196721,109,2142-07-17 08:12:00,0.0,0.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
4,217934.0,196721,109,2142-07-17 08:57:00,0.0,0.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,299251.0,131376,109,2142-07-07 12:00:00,81.0,10.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
328,299251.0,131376,109,2142-07-07 12:01:00,0.0,0.0,100.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
329,299251.0,131376,109,2142-07-07 12:33:00,0.0,0.0,0.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
330,299251.0,131376,109,2142-07-07 13:00:00,86.0,20.0,100.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False
331,299251.0,131376,109,2142-07-07 14:00:00,90.0,18.0,100.0,None,None,None,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
testdf.dtypes

ICUSTAY_ID             float64
HADM_ID                  int64
SUBJECT_ID               int64
CHARTTIME       datetime64[ns]
220045                 float64
220210                 float64
220277                 float64
1125                    object
128                     object
159                     object
161                     object
211                    float64
212                     object
550                     object
618                    float64
646                    float64
742                    float64
1484                    object
52                     float64
51                     float64
5815                   float64
5819                   float64
5820                   float64
8549                   float64
8553                   float64
8554                   float64
8368                   float64
224650                  object
220048                  object
227969                  object
MORTALITY                 bool
DIAGNOSIS               object
AGE                    float64
IS_DUMMY_ROW              bool
HAS_220045                bool
HAS_220210                bool
HAS_220277                bool
HAS_1125                  bool
HAS_128                   bool
HAS_159                   bool
HAS_161                   bool
HAS_211                   bool
HAS_212                   bool
HAS_550                   bool
HAS_618                   bool
HAS_646                   bool
HAS_742                   bool
HAS_1484                  bool
HAS_52                    bool
HAS_51                    bool
HAS_5815                  bool
HAS_5819                  bool
HAS_5820                  bool
HAS_8549                  bool
HAS_8553                  bool
HAS_8554                  bool
HAS_8368                  bool
HAS_224650                bool
HAS_220048                bool
HAS_227969                bool
dtype: object

In [ ]:
testdf['DIAGNOSIS'][testdf['DIAGNOSIS'].isnull()]

Series([], Name: DIAGNOSIS, dtype: object)

In [ ]:
testdf['HAS_220045'].describe()

count        74
unique        1
top       False
freq         74
Name: HAS_220045, dtype: object

In [ ]:
testdf.columns

Index(['ICUSTAY_ID',    'HADM_ID', 'SUBJECT_ID',       220045,       220210,
             220277,  'MORTALITY',        'AGE',         1125,          128,
                159,          161,          211,          212,          550,
                618,          646,          742,         1484,           52,
                 51,         5815,         5819,         5820,         8549,
               8553,         8554,         8368,       224650,       220048,
             227969, 'HAS_220045', 'HAS_220210', 'HAS_220277',   'HAS_1125',
          'HAS_128',    'HAS_159',    'HAS_161',    'HAS_211',    'HAS_212',
          'HAS_550',    'HAS_618',    'HAS_646',    'HAS_742',   'HAS_1484',
           'HAS_52',     'HAS_51',   'HAS_5815',   'HAS_5819',   'HAS_5820',
         'HAS_8549',   'HAS_8553',   'HAS_8554',   'HAS_8368', 'HAS_224650',
       'HAS_220048', 'HAS_227969'],
      dtype='object')

In [ ]:
list(dtypes.keys())

['ICUSTAY_ID',
 'HADM_ID',
 'SUBJECT_ID',
 220048,
 224650,
 227969,
 220045,
 220210,
 220277,
 1125,
 128,
 159,
 161,
 211,
 212,
 550,
 618,
 646,
 742,
 1484,
 52,
 51,
 5815,
 5819,
 5820,
 8549,
 8553,
 8554,
 8368]

In [ ]:
dtypes[128] = dtypes[220048]
dtypes[128]

dtype('O')

## Actual Processing

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)



newfile = "DATASET_GRU.csv"
newdf = pd.DataFrame()
if os.path.exists(os.path.join(datadir, newfile)):
    os.remove(os.path.join(datadir, newfile))

targets = list(dtypes.keys())[3:]
essentials = ['ICUSTAY_ID', 'HADM_ID', 'AGE', 'MORTALITY', 'SUBJECT_ID', 'DIAGNOSIS', 'CHARTTIME']
for i, chunk in enumerate(pd.read_csv(os.path.join(datadir, tables['CHARTEVENTS']), chunksize=10**6)):
    df = chunk[chunk['ICUSTAY_ID'].isin(icustay_id['ICUSTAY_ID'])]
    df = df[df['VALUE'].notna()]
    df = pivot(df)
    df = adjust_dataframe(df, list(targets), essentials, dtypes)
    # df = aggregate(df, ['ICUSTAY_ID', 'HADM_ID', 'SUBJECT_ID'])
    df = add_features(df, ['PATIENTS', 'ICUSTAYS', 'ADMISSIONS'])
    # grouped = df.groupby('ICUSTAY_ID')
    # df = pd.concat([process_patient(group) for name, group in grouped]).reset_index(drop=True)
    # df['IS_DUMMY_ROW'] = df['IS_DUMMY_ROW'].fillna(False).astype(bool)
    df = fill_nan(df)

    df['MORTALITY'] = df['MORTALITY'].astype('bool')
    df['HADM_ID'], df['SUBJECT_ID'] = df['HADM_ID'].astype('float64'), df['SUBJECT_ID'].astype('float64')

    if i!=0:
        if not newdf.columns.equals(df.columns):
            df = df.reindex(columns=newdf.columns)
        assert newdf.dtypes.equals(df.dtypes), "dtypes do not match"


    newdf = df

    with open(os.path.join(datadir, newfile), 'a') as f:
        df.to_csv(f, header=f.tell()==0, index=False)


    print(f"Saved {i}th chunk")

Saved 0th chunk
Saved 1th chunk
Saved 2th chunk
Saved 3th chunk
Saved 4th chunk
Saved 5th chunk
Saved 6th chunk
Saved 7th chunk
Saved 8th chunk
Saved 9th chunk
Saved 10th chunk
Saved 11th chunk
Saved 12th chunk
Saved 13th chunk
Saved 14th chunk
Saved 15th chunk
Saved 16th chunk
Saved 17th chunk
Saved 18th chunk
Saved 19th chunk
Saved 20th chunk
Saved 21th chunk
Saved 22th chunk
Saved 23th chunk
Saved 24th chunk
Saved 25th chunk
Saved 26th chunk
Saved 27th chunk
Saved 28th chunk
Saved 29th chunk
Saved 30th chunk
Saved 31th chunk
Saved 32th chunk
Saved 33th chunk
Saved 34th chunk
Saved 35th chunk
Saved 36th chunk
Saved 37th chunk
Saved 38th chunk
Saved 39th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 40th chunk
Saved 41th chunk
Saved 42th chunk
Saved 43th chunk
Saved 44th chunk
Saved 45th chunk
Saved 46th chunk
Saved 47th chunk
Saved 48th chunk
Saved 49th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 50th chunk
Saved 51th chunk
Saved 52th chunk
Saved 53th chunk
Saved 54th chunk
Saved 55th chunk
Saved 56th chunk
Saved 57th chunk
Saved 58th chunk
Saved 59th chunk
Saved 60th chunk
Saved 61th chunk
Saved 62th chunk
Saved 63th chunk
Saved 64th chunk
Saved 65th chunk
Saved 66th chunk
Saved 67th chunk
Saved 68th chunk
Saved 69th chunk
Saved 70th chunk
Saved 71th chunk
Saved 72th chunk
Saved 73th chunk
Saved 74th chunk
Saved 75th chunk
Saved 76th chunk
Saved 77th chunk
Saved 78th chunk
Saved 79th chunk
Saved 80th chunk
Saved 81th chunk
Saved 82th chunk
Saved 83th chunk
Saved 84th chunk
Saved 85th chunk
Saved 86th chunk
Saved 87th chunk
Saved 88th chunk
Saved 89th chunk
Saved 90th chunk
Saved 91th chunk
Saved 92th chunk
Saved 93th chunk
Saved 94th chunk
Saved 95th chunk
Saved 96th chunk
Saved 97th chunk
Saved 98th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 99th chunk
Saved 100th chunk
Saved 101th chunk
Saved 102th chunk
Saved 103th chunk
Saved 104th chunk
Saved 105th chunk
Saved 106th chunk
Saved 107th chunk
Saved 108th chunk
Saved 109th chunk
Saved 110th chunk
Saved 111th chunk
Saved 112th chunk
Saved 113th chunk
Saved 114th chunk
Saved 115th chunk
Saved 116th chunk
Saved 117th chunk
Saved 118th chunk
Saved 119th chunk
Saved 120th chunk
Saved 121th chunk
Saved 122th chunk
Saved 123th chunk
Saved 124th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 125th chunk
Saved 126th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 127th chunk
Saved 128th chunk
Saved 129th chunk
Saved 130th chunk
Saved 131th chunk
Saved 132th chunk
Saved 133th chunk
Saved 134th chunk
Saved 135th chunk
Saved 136th chunk
Saved 137th chunk
Saved 138th chunk
Saved 139th chunk
Saved 140th chunk
Saved 141th chunk
Saved 142th chunk
Saved 143th chunk
Saved 144th chunk
Saved 145th chunk
Saved 146th chunk
Saved 147th chunk
Saved 148th chunk
Saved 149th chunk
Saved 150th chunk
Saved 151th chunk
Saved 152th chunk
Saved 153th chunk
Saved 154th chunk
Saved 155th chunk
Saved 156th chunk
Saved 157th chunk
Saved 158th chunk
Saved 159th chunk
Saved 160th chunk
Saved 161th chunk
Saved 162th chunk
Saved 163th chunk
Saved 164th chunk
Saved 165th chunk
Saved 166th chunk
Saved 167th chunk
Saved 168th chunk
Saved 169th chunk
Saved 170th chunk
Saved 171th chunk
Saved 172th chunk
Saved 173th chunk
Saved 174th chunk
Saved 175th chunk
Saved 176th chunk
Saved 177th chunk
Saved 178th chunk
Saved 179th chunk
Saved 180th chunk
Saved 181th chunk
Saved 182th chunk
Saved 183th chunk
Saved 184th chunk
Saved 185th chunk
Saved 186th chunk
Saved 187th chunk
Saved 188th chunk
Saved 189th chunk
Saved 190th chunk
Saved 191th chunk
Saved 192th chunk

<ipython-input-12-0f36c5617e36>:13: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(pd.read_csv(os.path.join(datadir, tables['CHARTEVENTS']), chunksize=10**6)):

Saved 193th chunk
Saved 194th chunk
Saved 195th chunk
Saved 196th chunk
Saved 197th chunk
Saved 198th chunk
Saved 199th chunk
Saved 200th chunk
Saved 201th chunk
Saved 202th chunk
Saved 203th chunk
Saved 204th chunk
Saved 205th chunk
Saved 206th chunk
Saved 207th chunk
Saved 208th chunk
Saved 209th chunk
Saved 210th chunk
Saved 211th chunk
Saved 212th chunk
Saved 213th chunk
Saved 214th chunk
Saved 215th chunk
Saved 216th chunk
Saved 217th chunk
Saved 218th chunk
Saved 219th chunk
Saved 220th chunk
Saved 221th chunk
Saved 222th chunk
Saved 223th chunk
Saved 224th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 225th chunk
Saved 226th chunk
Saved 227th chunk
Saved 228th chunk
Saved 229th chunk
Saved 230th chunk
Saved 231th chunk
Saved 232th chunk
Saved 233th chunk
Saved 234th chunk
Saved 235th chunk
Saved 236th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 237th chunk
Saved 238th chunk
Saved 239th chunk
Saved 240th chunk
Saved 241th chunk
Saved 242th chunk
Saved 243th chunk
Saved 244th chunk
Saved 245th chunk
Saved 246th chunk
Saved 247th chunk
Saved 248th chunk
Saved 249th chunk
Saved 250th chunk
Saved 251th chunk
Saved 252th chunk
Saved 253th chunk
Saved 254th chunk

<ipython-input-12-0f36c5617e36>:13: DtypeWarning: Columns (8,10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(pd.read_csv(os.path.join(datadir, tables['CHARTEVENTS']), chunksize=10**6)):

Saved 255th chunk
Saved 256th chunk
Saved 257th chunk
Saved 258th chunk
Saved 259th chunk
Saved 260th chunk

<ipython-input-12-0f36c5617e36>:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  for i, chunk in enumerate(pd.read_csv(os.path.join(datadir, tables['CHARTEVENTS']), chunksize=10**6)):

Saved 261th chunk
Saved 262th chunk
Saved 263th chunk
Saved 264th chunk
Saved 265th chunk
Saved 266th chunk
Saved 267th chunk
Saved 268th chunk
Saved 269th chunk
Saved 270th chunk
Saved 271th chunk
Saved 272th chunk
Saved 273th chunk
Saved 274th chunk
Saved 275th chunk
Saved 276th chunk
Saved 277th chunk
Saved 278th chunk
Saved 279th chunk
Saved 280th chunk
Saved 281th chunk
Saved 282th chunk
Saved 283th chunk
Saved 284th chunk
Saved 285th chunk
Saved 286th chunk
Saved 287th chunk
Saved 288th chunk
Saved 289th chunk
Saved 290th chunk
Saved 291th chunk
Saved 292th chunk
Saved 293th chunk
Saved 294th chunk
Saved 295th chunk
Saved 296th chunk
Saved 297th chunk
Saved 298th chunk
Saved 299th chunk
Saved 300th chunk
Saved 301th chunk
Saved 302th chunk
Saved 303th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 304th chunk
Saved 305th chunk
Saved 306th chunk
Saved 307th chunk
Saved 308th chunk
Saved 309th chunk
Saved 310th chunk
Saved 311th chunk
Saved 312th chunk
Saved 313th chunk
Saved 314th chunk
Saved 315th chunk

<ipython-input-6-5c1ba6128e9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CHARTTIME'] = pd.to_datetime(df['CHARTTIME'])

Saved 316th chunk
Saved 317th chunk
Saved 318th chunk
Saved 319th chunk
Saved 320th chunk
Saved 321th chunk
Saved 322th chunk
Saved 323th chunk
Saved 324th chunk
Saved 325th chunk
Saved 326th chunk
Saved 327th chunk
Saved 328th chunk
Saved 329th chunk
Saved 330th chunk